### ISSUE TITLE
Editor default alt text is causing confusing alert message

### ISSUE THREAD

**Issue by cbirdsong** [itmaybejj/editoria11y-wp#9]
The editor adds placeholder alt text of "This image has an empty alt attribute; its file name is Image.jpg". This seems to be causing Editoria11y to flag them as images with URLs for alt text and not images with empty alt text?

![Two images in the Wordpress editor with "Image's text alternative is a URL" in the corner](https://user-images.githubusercontent.com/1672206/234073837-a92021c8-7ade-4b99-806e-a22f2fcbfa88.png)

**Comment by itmaybejj** [comment]
Uggh; you're right.

Hmmph; I can think of two directions to go with this -- any thoughts as to which you'd prefer?

1. Completely ignore images with that string in their alt. This would mean they wouldn't be flagged in the live editor until after the first save. Has the advantage of being really, really easy for me, and of not heckling people the moment they click insert...but skips a test until after the first save.
2. Add a parameter to the library to recognize certain strings as placeholders, so that these images would be immediately flagged as needing a manual check for having a blank alt.

**Comment by cbirdsong** [comment]
I'd do 1 if it's easy and then investigate the best way to do 2, but you may have to do 2? This is occurring for me with images that have definitely been saved.

**Comment by itmaybejj** [comment]
[Option two implemented and shipped!](https://github.com/itmaybejj/editoria11y-wp/compare/1.0.9...1.0.10)
